# Generated by Django 6.1 on 2026-08-27 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnfantToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enfant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='gallery.enfant')),
            ],
        ),
    ]
