# Generated by Django 6.1 on 2026-08-27 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_enfanttoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessin',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='date du dessin'),
        ),
    ]
