# Generated by Django 6.1 on 2026-08-27 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_dessin_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessin',
            name='aime',
            field=models.BooleanField(default=False, verbose_name='coup de cœur'),
        ),
        migrations.AddField(
            model_name='dessin',
            name='note',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note'),
        ),
    ]
